import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <div className="grid grid-cols-5 grid-rows-10  ">
        <div className="col-span-7 row-span-1 bg-amber-300">1
            
        </div>
        <div className=" h-screen col-span-5 row-span-8 row-start-2 bg-amber-700"> 
          {children}
        </div>
      </div>
  );
}
