import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/styles/globals.css";
import Navbar from "../components/Navbar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <div className="grid grid-cols-5 grid-rows-10 h-screen w-full overflow-hidden">
        <div className="col-span-5 row-span-1 bg-off-white align-middle flex items-center border-b-[3px] border-">
            <Navbar/>
        </div>
        <div className="col-span-5 row-span-9 row-start-2 bg-[#F9FAFB]"> 
          {children}
        </div>
      </div>
  );
}
