import type { Metadata } from "next";
import { Noto_Sans_Thai} from "next/font/google";
import "@/app/styles/globals.css";

const noto = Noto_Sans_Thai({
  subsets: ["thai"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${noto.className} antialiased`}>
      {children}
      </body>
    </html>
  );
}
